repos:
  - repo: https://github.com/ambv/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3.12
        args: [ --line-length=120 ]
        exclude: 'tests|scripts'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        args: [ "--unsafe" ]
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: detect-aws-credentials
        args: [ "--allow-missing-credentials" ]
      - id: detect-private-key
      - id: check-added-large-files
        args: [ "--maxkb=1024" ]
      - id: debug-statements
      - id: check-merge-conflict
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: ["--skip", "B104,B101", "--exclude", "tests/*"]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [ "--profile", "black", "--filter-files", "--line-length", "100" ]
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-unused-variables",
            "--remove-all-unused-imports",
            "--ignore-init-module-imports",
            "--exclude=tests/*",
            "--exclude=.venv/*",
          ]
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: [ "--max-line-length", "120", "--extend-ignore", "E203" ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [ "--ignore-missing-imports", "--namespace-packages", "--explicit-package-bases" ]
        additional_dependencies: [ 'types-requests' ]
